var Generator = require('yeoman-generator');

module.exports = class extends Generator {
  writing() {
    const pkgJson = {
      "name": this.directoryName,
      "version": "1.0.0",
      "description": "Workflow generated by yeoman for this project",
      "main": "gulpfile.js",
      "scripts": {
        "test": "echo \"Error: no test specified\" && exit 1"
      },
      "author": "Thomas Claude",
      "license": "ISC",
      "devDependencies": {
        "@babel/core": "^7.1.2",
        "@babel/preset-env": "^7.1.0",
        "babel-core": "^6.26.3",
        "babel-preset-env": "^1.7.0",
        "chalk": "^2.4.1",
        "gulp": "^3.9.1",
        "gulp-babel": "^8.0.0-beta.2",
        "gulp-connect": "^5.0.0",
        "gulp-imagemin": "^4.1.0",
        "gulp-pug": "^4.0.1",
        "gulp-sass": "^3.1.0",
        "pug": "^2.0.3"
      }
    };

    // Extend or create package.json file in destination path
    // Need to make a directory fill to answer.name

    this.fs.extendJSON(this.destinationPath(this.directoryName, '/package.json'), pkgJson);
  }
}
